### ISSUE TITLE
If possible, make building without bobril-build possible.

### ISSUE THREAD

**Issue by MicahZoltu** [Bobris/Bobril#100]
At the moment, the `bobril` NPM package doesn't contain compiled output.  It _only_ contains `index.ts`.  What is worse is that the `package.json` references `main: 'index.js'` which doesn't exist in the package (I'm surprised NPM let you publish like this).

If it is possible, it would be nice to be able to use this without having to use the custom tooling.  I believe at the _least_ this requires publishing NPM packages with pre-compiled `index.js` (this may require other changes as well, not sure).

**Comment by Bobris** [comment]
Hi, it is carefully stripped to make it as small as possible saving developers disk space. Would changing main to 'index.ts' help you in any way?

**Comment by MicahZoltu** [comment]
Probably not.  The `main` pointing at a non-existent `index.js` is just an invalid `package.json`.

On the more relevant topic of the missing `index.js`, is there a reason you don't distribute JS?  Is there something about the way Bobril works that makes it so it _wouldn't_ work if the JS was shipped with the NPM package?

**Comment by Bobris** [comment]
It would work of course, just that for intended usage with bobril-build it is useless and it just increase package size. But will consider to include it at least minified so it will not increase size too much.

**Comment by MicahZoltu** [comment]
What is the concern with increasing the NPM package size?  I can understand wanting to avoid increasing the size of the deployed code, but increasing an NPM package size from 300KB to 600KB feels unnecessary, especially when it prevents people from being able to use the library without custom build tooling.

**Comment by Bobris** [comment]
Will be implemented in version 13.0 roughly in week.

**Comment by Bobris** [comment]
Published in 13.0.0 beta
