### ISSUE TITLE
Style children with selectors?

### ISSUE THREAD

**Issue by YossiBenZaken** [Bobris/Bobril#105]
there a way to style children with selectors like focus?

**Comment by krewi1** [comment]
styleDef function accept second optional parametr for pseudo selectors (focus, hover, checked etc...).

**Comment by YossiBenZaken** [comment]
thank you!
and one more question
`        me.tag = 'div';
        me.children = [
            {
                tag: 'input', attrs:
                {
                    title: d.title,
                    id: d.placeholder,
                    name: d.placeholder,
                    placeholder: ' ',
                    type: d.type,
                    maxlength: d.maxlength,
                    autocapitalize: d.autocapitalize,
                    value: d.datactx.getValue(),
                   
                },
                data: { onChange: this.onChange }
            },
            {
                tag: 'label', children: d.placeholder, attrs: {
                    for: d.placeholder
                }
            }
        ];`
when i try to focus on text input on android its just get out of focus and i cant write anything

**Comment by krewi1** [comment]
We highly recommend using tsx instead of vanilla objects. But if you wanna stay with that that should be ok as well. Can you provide whole example.? Or minimal one could be even better.

**Comment by YossiBenZaken** [comment]
As soon as I try to write on Android, it opens and closes the keyboard straight (which doesn't happen on my computer and iPhone)

**Comment by krewi1** [comment]
where is onChange method implemented? I am not sure if this will do what you expect. onChange in data will be propably undefined and also that data are not consumed anywhere.

**Comment by Bobris** [comment]
I just see one mistake in label instead of "for" you should use "htmlFor". But more complete example would be needed to reproduce.

**Comment by YossiBenZaken** [comment]
Thank you
