### ISSUE TITLE
Quadient DC importing libraries

### ISSUE THREAD

**Issue by YossiBenZaken** [Bobris/Bobril#108]
i'm using the Quadient DC and i want to importing libraries to component that i build
but that give me error "Require is not defined" when its compile to js
there is a way to import libraries like material?

**Comment by Bobris** [comment]
It has to be done using existing features, look for example how "moment" library is done. Basicaly it is already bundled and exposed in global window scope. You cannot use commonjs directly. Quadient DC is only very simple in this regard by conditionally concatenating multiple javascripts in dependecy order.
