### ISSUE TITLE
local build not working

### ISSUE THREAD

**Issue by RadekMyska27** [Bobris/Bobril#111]
I have problem with local built, I am using for built bb

PS E:\Other_projects\VSC_ESP\testBobril> bb
Bobril-build core running C:\Users\rmysk.bbcore\1.34.0
Listening on http://localhost:8080/
Build started E:/Other_projects/VSC_ESP/testBobril
Npm install
npm WARN testbobril@1.0.0 No description
npm WARN testbobril@1.0.0 No repository field.

audited 1 package in 0.717s
found 0 vulnerabilities

during local built I received this error

Main file E:/Other_projects/VSC_ESP/testBobril/index.js not found
Using TypeScript version 4.1.2
JS Bundle length: 11758 SourceMap length: 517 T:28ms
package.json(1,1): Unused dependency bobril in package.json (-13)
Build done in 3.2s with no errors and 1 warning and has 3 files
Semantic check done in 4.3s with no errors and 1 warning

**Comment by krewi1** [comment]
You have to change main property in package.json to point to your index file. It will usually be something like index.ts or src/index.ts in bobril world.
