### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Gouigouix** [Bobris/Bobril#47]
Hello,

I use Bobril for the first time and I'm looking for [documentation](https://github.com/Bobris/Bobril/blob/master/src/bobril.md). You soon a complete documentation ?

- Into the [video ](https://youtu.be/iU8_5aKHURM?t=1013)he use b.createComponent(...) but I dont find this method!

Thank you.

**Comment by Bobris** [comment]
It basically creates factory function for component. You pass object with component functions. For render function it has slight magic to which sets me.tag to "div" and after it calls your real render function. If you don't need this feature use simpler b.createVirtualComponent instead.

I think best to look how it could be used is in my fresh material UI library:
https://github.com/bobril/bobril-m/blob/master/src/button.ts#L111
Usage:
https://github.com/bobril/bobril-m/blob/master/example.ts#L9
Working example:
http://bobril.com/bobril-m/

If you know React first parameter to created factory function is "props" - Bobril calls this "data". Second parameter are children, which are automatically added to "data" by factory function - it is simple sugar.
So then from any component function you can reference it as ctx.data.children.

It has really simple implementation: https://github.com/Bobris/Bobril/blob/master/src/bobril.helpers.ts#L15 - though it is very functional and generic so don't let that scare you...

**Comment by Bobris** [comment]
Also did you saw this?
http://www.codeproject.com/Articles/1044425/Bobril-I-Getting-started

**Comment by Gouigouix** [comment]
Cool,

I tested with `bobril.min.js` and `bobril.helpers.min.js` externally. Compact, but not very suitable in my workflow!

So I tried with `import * as b from 'bobril'` but when I compile with `"target": "es5"`, I have the following errors:

`Using tsc v1.8.0`
`node_modules/bobril/index.ts (200.12): error TS2339: Property 'assign' does not exist you type 'ObjectConstructor'.`
`node_modules/bobril/index.ts (201.12): error TS2339: Property 'assign' does not exist you type 'ObjectConstructor'.`
`node_modules/bobril/index.ts (218.28): error TS2339: Property 'assign' does not exist you type 'ObjectConstructor'.``

Furthermore, this is the full version when used import!
Finally, is there a posibility to use .tsx files?

Thank you.

**Comment by Bobris** [comment]
Best way to use bobril in npm is to use it together with bobril-build. It includes Typescript compilation, http server, watcher, bundler, asset management, localization management.
So start with:

     npm install bobril-build -g

when in some empty directory:

     npm init
     npm i bobril --save

create index.ts:

     import * as b from "bobril";
     b.init(()=>"Hello world");

Than start:

     bb

and open localhost:8080 in browser.

Best than it is to use VS Code to edit index.ts, save and refresh browser to see result.

Then you have finished your application start

     bb b

To build and minify whole application to dist directory.

**Comment by Bobris** [comment]
Regarding tsx: bobril-build currently does not support JSX. But I want to look at it in some future.

**Comment by Bobris** [comment]
To add why your plain tsc compilation does not work is because bobril needs ES6 lib.d.ts. But currently it is not possile to specify lib version and target JS version independently. This is also one of problems bobril-build solving. If you don't want to use bobril-build, just use ES6 target in TS and then use Babel to compile it down to ES3.

**Comment by Gouigouix** [comment]
Boris

Today, I use Grunt with `grunt-ts` for building a applications. Websites are multipages and I have a common JavaScript file and a specific file per page. This is not a SPA.

I looked `Bobril-Build` and that's a very interesting process. Now I would have can adapt to multipages.

Have you tested the cost of transpiling? https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016 ;o)

Thank you for your feedback.

**Comment by Bobris** [comment]
My target with bobril-build is really just SPA. Most of used optimizations are "whole program" - only by that I can achieve minimal bundle size. Thanks for that link will try it with bobril-build to compare. Additionaly bobril-build has way to mark functions as pure optimizing output beyond what's possible with rollup+uglifyjs.

I think you would be enough if bobril-build would just output commonjs modules so you could bundle them on your own with webpack (extracting commondly used bundles in your pages)

**Comment by Bobris** [comment]
Tested https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016 :-) bobril-build output size is 10152 which is second best and compilation speed is probably best too...
