### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by Gouigouix** [Bobris/Bobril#50]
Hi,

Is it possible to add the definition into [typings](https://github.com/typings/typings) ?

Thank you ;o)

**Comment by Bobris** [comment]
Could you explain why it would be even need (what usecase it would help and what should I even do?) Because I have https://github.com/Bobris/Bobril/blob/master/package/index.d.ts also TypeScript automatically opens index.d.ts if it does not find typings info in project.json.

**Comment by Gouigouix** [comment]
@Bobris I know, but I use brobil without node_modules import, and I thought it was a good thing. However typescript 2.0 should improve lib.d.ts modularity and new --lib support

Thx

**Comment by Bobris** [comment]
@Gouigouix Any reason why you do not use Bobril-build, it does really state of the art bundles with dead code elimination, extremely fast compilation, debugging with source-maps and much more?

**Comment by Gouigouix** [comment]
@Bobris Yes I would like to use it, but my workflow does not allow me today to do so. I use Bobril but not in a SPA!

I have another question about b.addRoot (), but I open another issue; o)

Thx
