### ISSUE TITLE
How to convert mouse click page position to element position?

### ISSUE THREAD

**Issue by LongerP** [Bobris/Bobril#57]
IBobrilMouseEvent contains page positions x and y. 
I need element postion.

My current solution:
```javascript
const position = b.convertPointFromPageToNode(ctx.me, x, y);
const scroll = b.getWindowScroll();
let cell = ctx.cellPositonConverter.getCellFromPositon(position[0] + scroll[0], position[1] + scroll[1]);
```

Is there any better way to convert it to element position with scroll support? 

THX
Pepa

**Comment by Bobris** [comment]
Need for adding window scroll manually is bug, this should solved inside `convertPointFromPageToNode`

**Comment by Bobris** [comment]
Your code was actually wrong (Scroll should be added before calling convertPointFromPageToNode).
Anyway to simplify this in Bobril 5.0.0 I removed convertPointFromPageToNode and added convertPointFromClientToNode with that you not need to mess with window scroll anymore.
