### ISSUE TITLE
First onChange event on select box

### ISSUE THREAD

**Issue by thenewby** [Bobris/Bobril#60]
Hello,

I have implemented a select box this way :
```
    const cePaxSelect = b.createComponent({
        render(ctx: IBobrilCtx, me: IBobrilNode) {
            me.tag = "select";
            me.className = "natural-select";
            me.children = this.createOptions(ctx.data);
        },
        onChange(ctx: IBobrilCtx, value: string) {
            // process value here ...
            b.invalidate();
        },
        createOptions(model: IBookingModel): IBobrilChildren {
        ...
```

The issue occured when we click on the select box, there is an onChange event that is launched, so, the first value in the list is selected. When a element is selected, I need to update the values inside this select box, but it create the issue of the click again. 
This does not appear on your exemple : http://bobris.github.io/Bobril/input/index.html

I have tried to create a event component to handle the onChange event inside it :
```
            me.component = {
                onChange(ctx: IBobrilCtx, value: string) {
                    console.log("select change : " + value);
                }
            };
```
but nothing occured.

thank you.

**Comment by Bobris** [comment]
Problem is probably I expect to have select controlled - you should set `me.attrs = { value: "currentvalue" }`

**Comment by thenewby** [comment]
Ok I understand the behavior :
- Without a default value selected, the corresponding change event is NOT called.
- With a default value, the corresponding change event is called (like in your exemple).

This creates an issue for me : 
- Without a default value, when I click on the select box, it launches the change event and select the first value. So, I refresh the select box content (it's necessary for me), and this issue come back when I click on it again.
- With an existing default value, the change event is launched at the page loading, and an item is selected, the first one, not the one corresponding to the given value, and I do not want it, not without user action. So, I refresh the select box content and after that it is ok although when I select the default value in the list, it does not work.
- With an empty value, the first value is selected endlessly (it create an infinite loop).

The solution that I will try is to create an empty default value, that will be like a placeholder, and check if the selected value is empty in the corresponding event and ignore it in this case.

**Comment by Bobris** [comment]
My example used double quotes in meaning here place current value variable. Not that you should use constant string.
There are many ways to fix it for example:

        interface IMyCtx extends b.IBobrilCtx {
              currentValue: string;
        }

        // ....
        init(ctx: IMyCtx) {
            ctx.currentValue = "";
        },
        render(ctx: IMyCtx, me: IBobrilNode) {
            me.tag = "select";
            me.className = "natural-select";
            me.attrs = { value: ctx.currentValue };
            me.children = this.createOptions(ctx.data);
        },
        onChange(ctx: IMyCtx, value: string) {
            ctx.currentValue = value;
            // process value here ...
            b.invalidate();
        },

**Comment by thenewby** [comment]
I used my solution with an empty default value and it worths.

I tried your solution too, but there are still issues : the first value of the select box is selected once, and the given default value cannot be selected at all in the select box (no event are launched, it does nothing when selecting it).

**Comment by Bobris** [comment]
That's why it is called onChange and not onSelect - when user selects already selected option there is no change.

**Comment by thenewby** [comment]
But there is no implemented onSelect event, isn't it ?

**Comment by Bobris** [comment]
True. From our usage we never need it.

Dne čt 1. 12. 2016 14:10 uživatel therry <notifications@github.com> napsal:

**Comment by thenewby** [comment]
ok. thanks.
