### ISSUE TITLE
Difference in component creation ways

### ISSUE THREAD

**Issue by thenewby** [Bobris/Bobril#61]
Hello,

I just want to know what is the difference between those 2 ways to create a component : 

1) declaration :
```
const myComponent: IBobrilComponent = {
     init(ctx: IBobrilCtx) {...},
     render(ctx: IBobrilCtx, me: IBobrilNode) {...}
```
use :
`{ component: myComponent, data: { model: model, passenger: passenger } }`

2) declaration :
```
const myComponent= b.createComponent({
     init(ctx: IBobrilCtx) {...},
     render(ctx: IBobrilCtx, me: IBobrilNode) {...}
```
use :
`myComponent( {...} )`

thank you.

**Comment by Bobris** [comment]
If you would use `b.createVirtualComponent` there would not be any difference. Second one is preferred because it is type safe. (I hope you are using bobril-build and TypeScript)
b.createComponent additionally sets `me.tag` to 'div' before calling render.
