### ISSUE TITLE
Switch bobril model

### ISSUE THREAD

**Issue by richy2509** [Bobris/Bobril#66]
Hi, 

I have 2 different models : 

model1: {}
model2: {}

When I click on a button, I'd like to change model. 

Could u, plz, tell me what's the best way. 

Best regards,

Richy

**Comment by Bobris** [comment]
Bobril is like React, model is "your" problem. For simple cases there is state in ctx of each component. After you change it just call b.invalidate(). Or just have something global. Or use Bobflux or Bobx. For nontrivial example look at bbExamples/gameoflife
