### ISSUE TITLE
is it possible write nested tag style use styledef?

### ISSUE THREAD

**Issue by hongmomanu** [Bobris/Bobril#75]
something like below...
 b.styleDef({
  color:'red';
  p:{
    color:'blue'
  }
}}

**Comment by Bobris** [comment]
You have to split it into 2 calls:

    let s1 = b.styleDef({ color: "red" });
    b.selectorStyleDef("."+s1+" p", { color: "blue" });

Generally this is not really good practice ... Better to be explicit and let name even nested style:

    let s1 = b.styleDef({ color: "red" });
    let s2 = b.styleDefEx(s1, { color: "blue" });
