### ISSUE TITLE
how to import gif file?

### ISSUE THREAD

**Issue by hongmomanu** [Bobris/Bobril#81]
png use sprite , but when use gif , the build is just  png file, the gif not work

**Comment by Bobris** [comment]
Gifs (usually animated and big would not be wise to merge into big bundle sprite image) you just need to use using `b.asset("relative/path/name.gif")` - which will be rewritten by bb2 to absolute path which you can use for example in `{ tag:"img", attrs: { src: b.asset("...") } }`
There is also another build-in feature in bb2, which will create src/assets.ts based on content of assets/ directory in project, you can then use these constants inside b.asset (or b.sprite) so you get nice intellisence for assets names. (This is shown here https://github.com/bobril/bbcore/tree/master/TestProjects/ImageQuality)
(BTW if you think this answer does not help you, feel free to reopen).
