### ISSUE TITLE
get rid of the cssFloat console error

### ISSUE THREAD

**Issue by svatal** [Bobris/Bobril#96]
Float was reserved keyword till ECMAScript 3 and reserved words actually only apply to Identifiers, so it's use as an object property is legal.
Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar

**Comment by Bobris** [comment]
Because Bobril access it though JavaScript and there only official name is cssFloat:

> If you're referring to this property from JavaScript as a member of the element.style object, you have to spell it as cssFloat. Also note that Internet Explorer versions 8 and older used styleFloat. This is an exception to the rule, that the name of the DOM member is the camel-case name of the dash-separated CSS name (due to the fact that "float" is a reserved word in JavaScript, as seen in the need to escape "class" as "className" and escape <label>'s "for" as "htmlFor").

But I could add feature to rename it automaticaly instead of reporting error.
